name: Deploy

on: workflow_dispatch

env:
  JAVA_VERSION: '1.8'
  JAVA_PACKAGE: jdk
  JAVA_ARCHITECTURE: x64

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          architecture: ${{ env.JAVA_ARCHITECTURE }}
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_ACTOR: ${{ secrets.MAVEN_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.MAVEN_USER_PASSWORD }}